# German message translation file for plpython
# Copyright (C) 2009 - 2013 PostgreSQL Global Development Group
# This file is distributed under the same license as the PostgreSQL package.
# Peter Eisentraut <peter_e@gmx.net>, 2009 - 2013.
#
# Use these quotes: „%s“
#
msgid ""
msgstr ""
"Project-Id-Version: PostgreSQL 9.3\n"
"Report-Msgid-Bugs-To: pgsql-bugs@postgresql.org\n"
"POT-Creation-Date: 2012-08-22 22:09+0000\n"
"PO-Revision-Date: 2013-03-04 21:46-0500\n"
"Last-Translator: Peter Eisentraut <peter_e@gmx.net>\n"
"Language-Team: German <peter_e@gmx.net>\n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"

#: plpy_cursorobject.c:98
#, c-format
msgid "plpy.cursor expected a query or a plan"
msgstr "plpy.cursor hat eine Anfrage oder einen Plan erwartet"

#: plpy_cursorobject.c:171
#, c-format
msgid "plpy.cursor takes a sequence as its second argument"
msgstr "plpy.cursor nimmt eine Sequenz als zweites Argument"

#: plpy_cursorobject.c:187 plpy_spi.c:222
#, c-format
msgid "could not execute plan"
msgstr "konnte Plan nicht ausführen"

#: plpy_cursorobject.c:190 plpy_spi.c:225
#, c-format
msgid "Expected sequence of %d argument, got %d: %s"
msgid_plural "Expected sequence of %d arguments, got %d: %s"
msgstr[0] "Sequenz aus %d Argument erwartet, aber %d erhalten: %s"
msgstr[1] "Sequenz aus %d Argumenten erwartet, aber %d erhalten: %s"

#: plpy_cursorobject.c:340
#, c-format
msgid "iterating a closed cursor"
msgstr "Iteration mit einem geschlossenen Cursor"

#: plpy_cursorobject.c:348 plpy_cursorobject.c:415
#, c-format
msgid "iterating a cursor in an aborted subtransaction"
msgstr "Iteration mit einem Cursor in einer abgebrochenen Transaktionen"

#: plpy_cursorobject.c:407
#, c-format
msgid "fetch from a closed cursor"
msgstr "Lesen aus einem geschlossenen Cursor"

#: plpy_cursorobject.c:486
#, c-format
msgid "closing a cursor in an aborted subtransaction"
msgstr "Schließen eines Cursors in einer abgebrochenen Subtransaktion"

#: plpy_elog.c:103 plpy_elog.c:104 plpy_plpymodule.c:420
#, c-format
msgid "%s"
msgstr "%s"

#: plpy_exec.c:90
#, c-format
msgid "unsupported set function return mode"
msgstr "nicht unterstützter Rückgabemodus für Funktion mit Mengenergebnis"

#: plpy_exec.c:91
#, c-format
msgid "PL/Python set-returning functions only support returning only value per call."
msgstr "PL/Python unterstützt für Funktionen mit Mengenergebnis nur das Zurückgeben von einem Wert pro Aufruf."

#: plpy_exec.c:103
#, c-format
msgid "returned object cannot be iterated"
msgstr "zurückgegebenes Objekt kann nicht iteriert werden"

#: plpy_exec.c:104
#, c-format
msgid "PL/Python set-returning functions must return an iterable object."
msgstr "PL/Python-Funktionen mit Mengenergebnis müssen ein iterierbares Objekt zurückgeben."

#: plpy_exec.c:129
#, c-format
msgid "error fetching next item from iterator"
msgstr "Fehler beim Auslesen des nächsten Elements vom Iterator"

#: plpy_exec.c:164
#, c-format
msgid "PL/Python function with return type \"void\" did not return None"
msgstr "PL/Python-Funktion mit Rückgabetyp „void“ hat nicht None zurückgegeben"

#: plpy_exec.c:288 plpy_exec.c:314
#, c-format
msgid "unexpected return value from trigger procedure"
msgstr "unerwarteter Rückgabewert von Triggerprozedur"

#: plpy_exec.c:289
#, c-format
msgid "Expected None or a string."
msgstr "Erwartete None oder eine Zeichenkette."

#: plpy_exec.c:304
#, c-format
msgid "PL/Python trigger function returned \"MODIFY\" in a DELETE trigger -- ignored"
msgstr "PL/Python-Funktion gab in einem DELETE-Trigger \"MODIFY\" zurück -- ignoriert"

#: plpy_exec.c:315
#, c-format
msgid "Expected None, \"OK\", \"SKIP\", or \"MODIFY\"."
msgstr "Erwartete None, \"OK\", \"SKIP\" oder \"MODIFY\"."

#: plpy_exec.c:396
#, c-format
msgid "PyList_SetItem() failed, while setting up arguments"
msgstr "PyList_SetItem() fehlgeschlagen, beim Einrichten der Argumente"

#: plpy_exec.c:400
#, c-format
msgid "PyDict_SetItemString() failed, while setting up arguments"
msgstr "PyDict_SetItemString() fehlgeschlagen, beim Einrichten der Argumente"

#: plpy_exec.c:412
#, c-format
msgid "function returning record called in context that cannot accept type record"
msgstr "Funktion, die einen Record zurückgibt, in einem Zusammenhang aufgerufen, der Typ record nicht verarbeiten kann"

#: plpy_exec.c:450
#, c-format
msgid "while creating return value"
msgstr "beim Erzeugen des Rückgabewerts"

#: plpy_exec.c:474
#, c-format
msgid "could not create new dictionary while building trigger arguments"
msgstr "konnte neues Dictionary nicht erzeugen, beim Aufbauen der Triggerargumente"

#: plpy_exec.c:664
#, c-format
msgid "TD[\"new\"] deleted, cannot modify row"
msgstr "TD[\"new\"] wurde gelöscht, kann Zeile nicht ändern"

#: plpy_exec.c:667
#, c-format
msgid "TD[\"new\"] is not a dictionary"
msgstr "TD[\"new\"] ist kein Dictionary"

#: plpy_exec.c:691
#, c-format
msgid "TD[\"new\"] dictionary key at ordinal position %d is not a string"
msgstr "Dictionary-Schlüssel auf Position %d in TD[\"new\"] ist keine Zeichenkette"

#: plpy_exec.c:697
#, c-format
msgid "key \"%s\" found in TD[\"new\"] does not exist as a column in the triggering row"
msgstr "in TD[\"new\"] gefundener Schlüssel „%s“ existiert nicht als Spalte in der den Trigger auslösenden Zeile"

#: plpy_exec.c:778
#, c-format
msgid "while modifying trigger row"
msgstr "beim Ändern der Triggerzeile"

#: plpy_exec.c:839
#, c-format
msgid "forcibly aborting a subtransaction that has not been exited"
msgstr "Abbruch einer Subtransaktion, die nicht beendet wurde, wird erzwungen"

#: plpy_main.c:100
#, c-format
msgid "Python major version mismatch in session"
msgstr "unpassende Python-Hauptversion für diese Sitzung"

#: plpy_main.c:101
#, c-format
msgid "This session has previously used Python major version %d, and it is now attempting to use Python major version %d."
msgstr "Diese Sitzung hat zuvor Python-Hauptversion %d verwendet und versucht nun Python-Hauptversion %d zu verwenden."

#: plpy_main.c:103
#, c-format
msgid "Start a new session to use a different Python major version."
msgstr "Starten Sie eine neue Sitzung, um eine andere Python-Hauptversion zu verwenden."

#: plpy_main.c:118
#, c-format
msgid "untrapped error in initialization"
msgstr "nicht abgefangener Fehler bei der Initialisierung"

#: plpy_main.c:141
#, c-format
msgid "could not import \"__main__\" module"
msgstr "konnte Modul „__main__“ nicht importieren"

#: plpy_main.c:146
#, c-format
msgid "could not create globals"
msgstr "konnte globale Objekte nicht erzeugen"

#: plpy_main.c:150
#, c-format
msgid "could not initialize globals"
msgstr "konnte globale Objekte nicht initialisieren"

#: plpy_main.c:347
#, c-format
msgid "PL/Python function \"%s\""
msgstr "PL/Python-Funktion „%s“"

#: plpy_main.c:354
#, c-format
msgid "PL/Python anonymous code block"
msgstr "anonymer PL/Python-Codeblock"

#: plpy_planobject.c:126
#, c-format
msgid "plan.status takes no arguments"
msgstr "plan.status nimmt keine Argumente"

#: plpy_plpymodule.c:178 plpy_plpymodule.c:181
#, c-format
msgid "could not import \"plpy\" module"
msgstr "konnte Modul „plpy“ nicht importieren"

#: plpy_plpymodule.c:196
#, c-format
msgid "could not add the spiexceptions module"
msgstr "konnte das Modul „spiexceptions“ nicht hinzufügen"

#: plpy_plpymodule.c:217
#, c-format
msgid "could not create the base SPI exceptions"
msgstr "konnte die SPI-Basisausnahmen nicht erzeugen"

#: plpy_plpymodule.c:253 plpy_plpymodule.c:257
#, c-format
msgid "could not generate SPI exceptions"
msgstr "konnte SPI-Ausnahmen nicht erzeugen"

#: plpy_plpymodule.c:388
#, c-format
msgid "could not unpack arguments in plpy.elog"
msgstr "konnte Argumente in plpy.elog nicht entpacken"

#: plpy_plpymodule.c:396
msgid "could not parse error message in plpy.elog"
msgstr "konnte Fehlermeldung in plpy.elog nicht parsen"

#: plpy_procedure.c:194
#, c-format
msgid "trigger functions can only be called as triggers"
msgstr "Triggerfunktionen können nur als Trigger aufgerufen werden"

#: plpy_procedure.c:199 plpy_typeio.c:406
#, c-format
msgid "PL/Python functions cannot return type %s"
msgstr "PL/Python-Funktionen können keinen Rückgabetyp %s haben"

#: plpy_procedure.c:281
#, c-format
msgid "PL/Python functions cannot accept type %s"
msgstr "PL/Python-Funktionen können Typ %s nicht annehmen"

#: plpy_procedure.c:377
#, c-format
msgid "could not compile PL/Python function \"%s\""
msgstr "konnte PL/Python-Funktion „%s“ nicht kompilieren"

#: plpy_procedure.c:380
#, c-format
msgid "could not compile anonymous PL/Python code block"
msgstr "konnte anonymen PL/Python-Codeblock nicht kompilieren"

#: plpy_resultobject.c:145 plpy_resultobject.c:165 plpy_resultobject.c:185
#, c-format
msgid "command did not produce a result set"
msgstr "Befehl hat keine Ergebnismenge erzeugt"

#: plpy_spi.c:56
#, c-format
msgid "second argument of plpy.prepare must be a sequence"
msgstr "zweites Argument von plpy.prepare muss eine Sequenz sein"

#: plpy_spi.c:105
#, c-format
msgid "plpy.prepare: type name at ordinal position %d is not a string"
msgstr "plpy.prepare: Typname auf Position %d ist keine Zeichenkette"

#: plpy_spi.c:137
#, c-format
msgid "plpy.prepare does not support composite types"
msgstr "plpy.prepare unterstützt keine zusammengesetzten Datentypen"

#: plpy_spi.c:187
#, c-format
msgid "plpy.execute expected a query or a plan"
msgstr "plpy.execute hat eine Anfrage oder einen Plan erwartet"

#: plpy_spi.c:206
#, c-format
msgid "plpy.execute takes a sequence as its second argument"
msgstr "plpy.execute nimmt eine Sequenz als zweites Argument"

#: plpy_spi.c:330
#, c-format
msgid "SPI_execute_plan failed: %s"
msgstr "SPI_execute_plan fehlgeschlagen: %s"

#: plpy_spi.c:372
#, c-format
msgid "SPI_execute failed: %s"
msgstr "SPI_execute fehlgeschlagen: %s"

#: plpy_spi.c:439
#, c-format
msgid "unrecognized error in PLy_spi_execute_fetch_result"
msgstr "unbekannter Fehler in PLy_spi_execute_fetch_result"

#: plpy_subxactobject.c:122
#, c-format
msgid "this subtransaction has already been entered"
msgstr "diese Subtransaktion wurde bereits begonnen"

#: plpy_subxactobject.c:128 plpy_subxactobject.c:180
#, c-format
msgid "this subtransaction has already been exited"
msgstr "diese Subtransaktion wurde bereits beendet"

#: plpy_subxactobject.c:174
#, c-format
msgid "this subtransaction has not been entered"
msgstr "diese Subtransaktion wurde nicht begonnen"

#: plpy_subxactobject.c:186
#, c-format
msgid "there is no subtransaction to exit from"
msgstr "es gibt keine Subtransaktion zu beenden"

#: plpy_typeio.c:291
#, c-format
msgid "could not create new dictionary"
msgstr "konnte neues Dictionary nicht erzeugen"

#: plpy_typeio.c:408
#, c-format
msgid "PL/Python does not support conversion to arrays of row types."
msgstr "PL/Python unterstützt die Umwandlung in Arrays von Zeilentypen nicht."

#: plpy_typeio.c:584
#, c-format
msgid "cannot convert multidimensional array to Python list"
msgstr "kann mehrdimensionales Array nicht in Python-Liste umwandeln"

#: plpy_typeio.c:585
#, c-format
msgid "PL/Python only supports one-dimensional arrays."
msgstr "PL/Python unterstützt nur eindimensionale Arrays."

#: plpy_typeio.c:591
#, c-format
msgid "could not create new Python list"
msgstr "konnte neue Python-Liste nicht erzeugen"

#: plpy_typeio.c:650
#, c-format
msgid "could not create bytes representation of Python object"
msgstr "konnte Bytes-Darstellung eines Python-Objektes nicht erzeugen"

#: plpy_typeio.c:742
#, c-format
msgid "could not create string representation of Python object"
msgstr "konnte Zeichenkettendarstellung eines Python-Objektes nicht erzeugen"

#: plpy_typeio.c:753
#, c-format
msgid "could not convert Python object into cstring: Python string representation appears to contain null bytes"
msgstr "konnte Python-Objekt nicht in cstring umwandeln: Python-Zeichenkettendarstellung enthält anscheinend Null-Bytes"

#: plpy_typeio.c:787
#, c-format
msgid "return value of function with array return type is not a Python sequence"
msgstr "Rückgabewert von Funktion mit Array-Rückgabetyp ist keine Python-Sequenz"

#: plpy_typeio.c:886
#, c-format
msgid "key \"%s\" not found in mapping"
msgstr "Schlüssel „%s“ nicht in Mapping gefunden"

#: plpy_typeio.c:887
#, c-format
msgid "To return null in a column, add the value None to the mapping with the key named after the column."
msgstr "Um einen NULL-Wert in einer Spalte zurückzugeben, muss der Wert None mit einem nach der Spalte benannten Schlüssel in das Mapping eingefügt werden."

#: plpy_typeio.c:935
#, c-format
msgid "length of returned sequence did not match number of columns in row"
msgstr "Länge der zurückgegebenen Sequenz hat nicht mit der Anzahl der Spalten in der Zeile übereingestimmt"

#: plpy_typeio.c:1043
#, c-format
msgid "attribute \"%s\" does not exist in Python object"
msgstr "Attribut „%s“ existiert nicht in Python-Objekt"

#: plpy_typeio.c:1044
#, c-format
msgid "To return null in a column, let the returned object have an attribute named after column with value None."
msgstr "Um einen NULL-Wert in einer Spalte zurückzugeben, muss das zurückzugebende Objekt ein nach der Spalte benanntes Attribut mit dem Wert None haben."

#: plpy_util.c:70
#, c-format
msgid "could not convert Python Unicode object to bytes"
msgstr "konnte Python-Unicode-Objekt nicht in Bytes umwandeln"

#: plpy_util.c:75
#, c-format
msgid "could not extract bytes from encoded string"
msgstr "konnte kodierte Zeichenkette nicht in Bytes umwandeln"
