#
# Translation of plpython to Italian
# PostgreSQL Project
#
# Associazione Culturale ITPUG - Italian PostgreSQL Users Group
# http://www.itpug.org/ - info@itpug.org
#
# Traduttori:
#  * Flavio Spada <f.spada@sbv.mi.it>
# 
# Revisori:
#  * Gabriele Bartolini <gabriele.bartolini@2ndQuadrant.it>
#
# Copyright (c) 2010, Associazione Culturale ITPUG
# Distributed under the same license of the PostgreSQL project
#
msgid ""
msgstr ""
"Project-Id-Version: plpython-it\n"
"Report-Msgid-Bugs-To: pgsql-bugs@postgresql.org\n"
"POT-Creation-Date: 2010-03-26 13:15+0000\n"
"PO-Revision-Date: 2010-03-27 12:44:19+0100\n"
"Last-Translator: Gabriele Bartolini <gabriele.bartolini@2ndquadrant.it>\n"
"Language-Team: Gruppo traduzioni ITPUG <traduzioni@itpug.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
"X-Generator: KBabel 1.11.4\n"

#: plpython.c:418
#, c-format
msgid "PL/Python function \"%s\""
msgstr "funzione PL/Python \"%s\""

#: plpython.c:424
msgid "PL/Python anonymous code block"
msgstr "codice di blocco anonimo in PL/Python"

#: plpython.c:431
msgid "while modifying trigger row"
msgstr "durante la modifica della riga trigger"

#: plpython.c:438
msgid "while creating return value"
msgstr "durante la creazione del valore di ritorno"

#: plpython.c:604
#: plpython.c:630
msgid "unexpected return value from trigger procedure"
msgstr "valore di ritorno inatteso dalla prodedura di trigger"

#: plpython.c:605
msgid "Expected None or a string."
msgstr "Atteso None o una stringa."

#: plpython.c:620
msgid "PL/Python trigger function returned \"MODIFY\" in a DELETE trigger -- ignored"
msgstr "la funzione PL/Python trigger ha restituito \"MODIFY\" in un trigger DELETE -- ignorato"

#: plpython.c:631
msgid "Expected None, \"OK\", \"SKIP\", or \"MODIFY\"."
msgstr "Atteso None, \"OK\", \"SKIP\", o \"MODIFY\"."

#: plpython.c:683
msgid "TD[\"new\"] deleted, cannot modify row"
msgstr "TD[\"new\"] cancellato, impossibile modificare la riga"

#: plpython.c:686
msgid "TD[\"new\"] is not a dictionary"
msgstr "TD[\"new\"] non è un dizionario"

#: plpython.c:710
#, c-format
msgid "TD[\"new\"] dictionary key at ordinal position %d is not a string"
msgstr "la chiave di dizionario TD[\"new\"] alla posizione %d non è una stringa"

#: plpython.c:716
#, c-format
msgid "key \"%s\" found in TD[\"new\"] does not exist as a column in the triggering row"
msgstr "la chiave \"%s\" trovata in TD[\"new\"] non esiste come colonna nella riga del trigger"

#: plpython.c:810
msgid "could not create new dictionary while building trigger arguments"
msgstr "impossibile creare un nuovo dizionario mentre si stanno costruendo gli argomenti del trigger"

#: plpython.c:1017
msgid "unsupported set function return mode"
msgstr "modalità di ritorno della funzione set non supportata"

#: plpython.c:1018
msgid "PL/Python set-returning functions only support returning only value per call."
msgstr "le funzioni set-returning di PL/Python supportano il valore di ritorno solo una volta per chiamata"

#: plpython.c:1030
msgid "returned object cannot be iterated"
msgstr "l'oggetto ritornato non può essere iterato"

#: plpython.c:1031
msgid "PL/Python set-returning functions must return an iterable object."
msgstr "le funzioni set-returning di PL/Python devono tornare un oggetto iterabile"

#: plpython.c:1058
msgid "error fetching next item from iterator"
msgstr "errore nell'ottenere l'elemento successivo dall'iteratore"

#: plpython.c:1080
msgid "PL/Python function with return type \"void\" did not return None"
msgstr "la funzione PL/Python con valore di ritorno \"void\" non ha restituito None"

#: plpython.c:1237
msgid "PyList_SetItem() failed, while setting up arguments"
msgstr "PyList_SetItem() è fallita durante l'impostazione degli argomenti"

#: plpython.c:1241
msgid "PyDict_SetItemString() failed, while setting up arguments"
msgstr "PyDict_SetItemString() è fallita durante l'impostazione degli argomenti"

#: plpython.c:1416
msgid "trigger functions can only be called as triggers"
msgstr "le funzioni trigger possono essere chiamate solo come trigger"

#: plpython.c:1420
#: plpython.c:1800
#, c-format
msgid "PL/Python functions cannot return type %s"
msgstr "le funzioni PL/Python non possono tornare il tipo %s"

#: plpython.c:1498
#, c-format
msgid "PL/Python functions cannot accept type %s"
msgstr "le funzioni PL/Python non possono accettare il tipo %s"

#: plpython.c:1592
#, c-format
msgid "could not compile PL/Python function \"%s\""
msgstr "impossibile compilare la funzione PL/Python \"%s\""

#: plpython.c:1802
msgid "PL/Python does not support conversion to arrays of row types."
msgstr ""

#: plpython.c:1996
msgid "cannot convert multidimensional array to Python list"
msgstr ""

#: plpython.c:1997
msgid "PL/Python only supports one-dimensional arrays."
msgstr ""

#: plpython.c:2031
msgid "could not create new dictionary"
msgstr "impossibile creare il nuovo dizionario"

#: plpython.c:2107
msgid "could not create bytes representation of Python object"
msgstr "impossibile creare la rappresentazione di tipo byte dell'oggetto Python"

#: plpython.c:2163
msgid "could not create string representation of Python object"
msgstr "impossibile creare la rappresentazione di tipo stringa dell'oggetto Python"

#: plpython.c:2174
msgid "could not convert Python object into cstring: Python string representation appears to contain null bytes"
msgstr ""

#: plpython.c:2207
msgid "return value of function with array return type is not a Python sequence"
msgstr ""

#: plpython.c:2282
#, c-format
msgid "key \"%s\" not found in mapping"
msgstr "la chiave \"%s\" non è stata trovata nel dizionario"

#: plpython.c:2283
msgid "To return null in a column, add the value None to the mapping with the key named after the column."
msgstr "Per ritornare null in una colonna, inserire nella mappa il valore None in corrispondenza del nome di colonna come chiave."

#: plpython.c:2326
msgid "length of returned sequence did not match number of columns in row"
msgstr "la lunghezza della sequenza ritornata non rispetta il numero di colonne presenti nella riga"

#: plpython.c:2419
#, c-format
msgid "attribute \"%s\" does not exist in Python object"
msgstr "l'attributo \"%s\" non esiste nell'oggetto Python"

#: plpython.c:2420
msgid "To return null in a column, let the returned object have an attribute named after column with value None."
msgstr "Per ritornare null in una colonna, assicurarsi che all'oggetto di ritorno corrisponda nel dizionario un attributo con valore None."

#: plpython.c:2654
msgid "plan.status takes no arguments"
msgstr "plan.status non accetta argomenti"

#: plpython.c:2778
#: plpython.c:2921
msgid "transaction aborted"
msgstr "transazione abortita"

#: plpython.c:2785
msgid "invalid arguments for plpy.prepare"
msgstr "argomenti non validi per plpy.prepare"

#: plpython.c:2792
msgid "second argument of plpy.prepare must be a sequence"
msgstr "il secondo argomento di plpy.prepare deve essere una sequenza"

#: plpython.c:2842
#, c-format
msgid "plpy.prepare: type name at ordinal position %d is not a string"
msgstr "plpy.prepare: il nome del tipo nella posizione %d non è una stringa"

#: plpython.c:2869
msgid "plpy.prepare does not support composite types"
msgstr "plpy.prepare non supporta tipi composti"

#: plpython.c:2898
msgid "unrecognized error in PLy_spi_prepare"
msgstr "errore non riconosciuto in PLy_spi_prepare"

#: plpython.c:2934
msgid "plpy.execute expected a query or a plan"
msgstr "plpy.execute si aspetta una query o un plan"

#: plpython.c:2951
msgid "plpy.execute takes a sequence as its second argument"
msgstr "plpy.execute richiede una sequenza come secondo argomento"

#: plpython.c:2967
msgid "could not execute plan"
msgstr "impossibile eseguire il piano"

#: plpython.c:2970
#, c-format
msgid "Expected sequence of %d argument, got %d: %s"
msgid_plural "Expected sequence of %d arguments, got %d: %s"
msgstr[0] "Sequenza attesa per l'argomento %d, ricevuto %d: %s"
msgstr[1] "Sequenza attesa di %d argomenti, ricevuti %d: %s"

#: plpython.c:3047
msgid "unrecognized error in PLy_spi_execute_plan"
msgstr "errore non riconosciuto nella funzione PLy_spi_execute_plan"

#: plpython.c:3066
#, c-format
msgid "SPI_execute_plan failed: %s"
msgstr "SPI_execute_plan ha fallito: %s"

#: plpython.c:3093
msgid "unrecognized error in PLy_spi_execute_query"
msgstr "errore non riconosciuto nella funzione PLy_spi_execute_query"

#: plpython.c:3102
#, c-format
msgid "SPI_execute failed: %s"
msgstr "SPI_execute ha fallito: %s"

#: plpython.c:3162
msgid "unrecognized error in PLy_spi_execute_fetch_result"
msgstr "errore non riconosciuto nella funzione PLy_spi_execute_fetch_result"

#: plpython.c:3213
msgid "untrapped error in initialization"
msgstr "errore non catturato durante l'inizializzazione"

#: plpython.c:3216
msgid "could not create procedure cache"
msgstr "impossibile creare la procedura cache"

#: plpython.c:3228
msgid "could not import \"__main__\" module"
msgstr "impossibile importare il modulo \"__main__\""

#: plpython.c:3235
msgid "could not initialize globals"
msgstr "impossibile inizializzare le variabili globali"

#: plpython.c:3353
msgid "could not parse error message in plpy.elog"
msgstr "impossibile interpretare il messaggio di errore in plpy.elog"

#: plpython.c:3482
#: plpython.c:3486
#, c-format
msgid "PL/Python: %s"
msgstr "PL/Python: %s"

#: plpython.c:3483
#, c-format
msgid "%s"
msgstr "%s"

#: plpython.c:3596
msgid "out of memory"
msgstr "memoria esaurita"

#: plpython.c:3650
msgid "could not convert Python Unicode object to PostgreSQL server encoding"
msgstr ""

#~ msgid ""
#~ "could not compute string representation of Python object in PL/Python "
#~ "function \"%s\" while modifying trigger row"
#~ msgstr ""
#~ "impossibile calcolare la rappresentazione di tipo stringa dell'oggetto "
#~ "Python nella funzione PL/Python \"%s\" mentre si sta modificando la riga "
#~ "di trigger"

#~ msgid ""
#~ "could not create string representation of Python object in PL/Python "
#~ "function \"%s\" while creating return value"
#~ msgstr ""
#~ "impossibile creare una rappresentazione di tipo stringa dell'oggetto "
#~ "Python nella funzione PL/Python \"%s\" durante la creazione del valore di "
#~ "ritorno"

#~ msgid "PL/Python function \"%s\" failed"
#~ msgstr "la funzione PL/Python \"%s\" è fallita"
